[package]
name = "miner-rust"
version = "0.1.0"
authors = ["rllola <rllola80@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.10", features = ["blocking","json"] }
serde_json = "1.0.60"
hex = "0.4.2"
hmac-sha256 = "0.1.6"
rust-scrypt = "1.3.0"